import type { Metadata } from "next";
import "./globals.css";
import { inter, interBold } from "./fonts/Inter";
import { jura, juraBold } from "./fonts/Jura";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`overflow-x-hidden ${interBold.variable} ${inter.variable} ${jura.variable} ${juraBold.variable} relative z-10 font-inter`}
      >
        {children}
      </body>
    </html>
  );
}
